### ISSUE TITLE
Issue #2 - Database Schema

### ISSUE THREAD

**Issue by keginzburg** [lsherman98/EventLite#3]
# Database Schema
- [X] Contains correct datatypes
- [X] Contains appropriate constraints/details
  - [X] primary key
  - [X] not null
  - [X] unique
  - [X] indexed
  - [X] foreign key
- [X] Contains bullet points after the table that state which foreign keys will reference to which table, or references to the associations which will be made
 - [X] foreign key and table name are lowercased, snake_cased and `back_ticked`
- [X] Correctly formatted
  - [X] schema is written in a table format
  - [X] the table's name are lowercased, snake_cased and `back_ticked`
  - [X] the table header column names are bolded
  - [X] columns names are lowercased and snaked_cased and `back_ticked`

## Comments
1. Should `Users` have a unique index on their `email` column as well?
2. Your `Users` currently `belongs_to: event, through: registration_table`, but if your `Registrations` table connects Users to Events, then wouldn't a User have many `registrations` instead?
3. Great info for the `Events` table. Events are this app's selling point, so the more information, the better.
4. Should your `Event Registrations` table have `belongs_to` associations? Can that table also have a `quantity` if a User purchases multiple registrations to an Event?
5. Should your `Bookmarks` table have `belongs_to` associations?

**Comment by lsherman98** [comment]
Im a little lost on how all of these associations should look. I know its a many-to-many relationship, just not sure exactly how to write these out. 

Also the registration and bookmarks tables are exactly the same, do they need to be two separate tables?

**Comment by lsherman98** [comment]
Re wrote the associations, i think it makes more sense now. 

There are two many to many relationships. 
User has many registrations <> Event has many registrations
User has many bookmarks <> Event has many bookmarks

**Comment by keginzburg** [comment]
Yup, this looks solid now. Our Registrations and Bookmarks are almost no different than Likes in that they just connect Users to Events. Solid work.
