### ISSUE TITLE
Issue #3 - Sample State

### ISSUE THREAD

**Issue by keginzburg** [lsherman98/EventLite#4]
# Sample State
- [X] State shape is flat!
- [X] State's keys are camelCased
- [X] All keys within the values in the state are accessible in the schema
- [X] Correctly formatted
  - [X] Sample state is rendered with triple backticks, and the language ` ```javascript...``` `). This will display the state as a code block instead of a giant line of text 
  - [X] Top level slices
    - [X] `entities`
    - [X] `session`
    - [X] `errors` (here or in `ui`)
    - [X] `ui` (if needed)
  - [X] Should NOT have nested slices, aka `comments` inside of `posts`
   + Some info from other tables is ok, for instance:
    + the author username and imageurl for a post. basically any info that the user can't change
    + like count and a boolean on whether the user likes the post instead of a likes slice

## Comments
1. I believe you are missing event registrations within your frontend state.

**Comment by lsherman98** [comment]
Does it make sense to have arrays here? 
Registrations slice where keys are event ids and value is array of userIds and then an array of eventIds in each users state of events they are signed up for?

Same issue with bookmarks, the state would get extremely big if i need a new object for every event/user & user/event pair.

**Comment by lsherman98** [comment]
There is now two separate sample states, a user state (for use profile), and a global state(for the events index page etc). Let me know if this makes sense.
