### ISSUE TITLE
Issue #4 - Backend Routes

### ISSUE THREAD

**Issue by keginzburg** [lsherman98/EventLite#5]
# Backend Routes
- [X] Contains the following sections: HTML, API Endpoints(Backend)
- [X] Each route has a description
- [X] API Endpoint routes contains wildcard variables written in `snake_case`
- [ ] Routes does not contain [superfluous routes](https://github.com/appacademy/curriculum/blob/master/rails/readings/routing-part-ii.md)
- [ ] Have API routes that will allow the front end to get all info it needs and does not have unneeded routes:
  + probably doesn't need a `GET likes` api endpoint because that info comes through the post show

## Comments
1. I recommend we avoid a `PUT` route for our users resource. We can add this later, but we should aim to have basic User Auth for users for now.
2. Do we need a `GET /api/users` route to fetch the user info that relates to a single event? Can we not pull a single event's details with `GET /api/events/:id` and then pass that user info down as well?
3. Do we need a `GET /api/events/:id` route to fetch the events created by a specific user? Once again, can we not pull a single user's details with `GET /api/users/:id` and then pass their events info down as well? Don't forget about the Rails associations in the backend.
4. All of the `GET` routes for bookmarks and registrations are superfluous. We can discuss later.

**Comment by lsherman98** [comment]
got rid of superfluous back end routes
